image:
  file: Dockerfile

ports:
  - port: 8001

tasks:
  -  init: mkdir /workspace/my-gitpod-basics/gitpod-logs                        &&
           touch /workspace/my-gitpod-basics/gitpod-logs/myGitpodLog.txt 
           
             
             
     command: echo "Start the .gitpod.yml installation"         &>> /workspace/my-gitpod-basics/gitpod-logs/myGitpodLog.txt     && 
     
     
     
              echo "Starting Apache"                            &>> /workspace/my-gitpod-basics/gitpod-logs/myGitpodLog.txt      &&   
              apachectl start                                                                                                    &&
              gp await-port 8001                                                                                                 && 
              gp preview $(gp url 8001)                                                                                          &&
              
              
              
              echo "Last line in logs"                          &>> /workspace/my-gitpod-basics/gitpod-logs/myGitpodLog.txt    
              
              
              
